# **RBOT 240 - Week 9 Exercises**

Complete 3 of the following exercises.

The numbered exercises below are from the Sutton & Barto book [Reinforcement Learning: An Introduction](https://www.andrew.cmu.edu/course/10-703/textbook/BartoSutton.pdf) from this week's reading material.  Please see the book for more context on these problems.

---

# <font color="blue">My selected three questions are:</font>

<font color="blue">- <b>Discussion Exercise 3.1</b></font>

<font color="blue">- <b>Discussion Exercise 3.2</b></font>

<font color="blue">- <b>Programming Exercise P1</b></font>

---

## Problem Exercises

**(Exercise 3.14)** The Bellman equation (3.14) must hold for each state for the value function $v_\pi$ shown in Figure 3.2 (right) of Example 3.5. Show numerically that this equation holds for the center state, valued at +0.7, with respect to its four neighboring states, valued at +2.3, +0.4, 0.4, and +0.7. (These numbers are accurate only to one decimal place.)

**(Exercise 4.3)** What are the equations analogous to (4.3), (4.4), and (4.5) for the action-value function $q_\pi$ and its successive approximation by a sequence of functions $q_0$, $q_1$, $q_2$,...?

**(Exercise 4.5)** How would policy iteration be defined for action values? Give a complete algorithm for computing $q_*$, analogous to that on page 80 for computing $v_*$. Please pay special attention to this exercise, because the ideas involved will be used throughout the rest of the book.

**(Exercise 4.10)** What is the analog of the value iteration update (4.10) for action values, $q_{k+1}(s,a)$?

## Discussion Exercises

**<font color="blue">(Exercise 3.1)** Devise three example tasks of your own that fit into the MDP framework, identifying for each its states, actions, and rewards. Make the three examples as different from each other as possible. The framework is abstract and flexible and can be applied in many different ways. Stretch its limits in some way in at least one of your examples.</font>

<font color="green"><u><b>Answer</b></u></font>

1.   **Finance**: Based on this paper, "***Using Markov Decision Processes to Solve a Portfolio Allocation Problem*** [1]", **MDP** can be used to learn the  optimal time to buy or sell stocks based on the current available information. 

    In this case the **state** would be the size(amount of dollars) and direction (+/-) of the real-time return of the stock.
    
    The **action** might be the quantities (how much of a stock to buy or sell) and whether to buy or sell. 

    The **reward** can be the corresponding profit or loss from this action. 
2.   **Queues**: Based on this article, "***Application of reinforcement learning to control traffic signals*** [2]", **MDP** can be used for ***Traffic Control***. For example, we want to decide the duration of traffic lights in an intersection maximizing the number cars passing the intersection without stopping.

    In this case the **state** is represented of a traffic environments such as color of the traffic light (red, green) in each directions, the duration of the traffic light and number of cars.

    The **action** is whether or not to change the traffic light.

    The **reward** is the number of cars passing the intersection in the next time step minus some sort of discount for the traffic blocked in the other direction.
3.   **Robotics**: Robot can learn of how to escape a maze or any kind of navigation solver by using **MDP**.[3] 

    The **state** could be the robots position and its orientation in the maze. 
    
    The **actions** could be one of the following: to move forward, backwards, or turn 90 degrees. 
    
    The **reward** could be <font color="red">-1</font> if the robot hit a wall and <font color="green">+1</font> if the robot find an exit of the maze.

[1] https://cs.brown.edu/research/pubs/theses/ugrad/2005/dbooksta.pdf

[2] https://blogs.sas.com/content/subconsciousmusings/2020/12/16/reinforcement-learning-neurips/

[3] https://web.cs.dal.ca/~tt/robotics/415511_MDP&RL.pdf



**<font color="blue">(Exercise 3.2)** Is the MDP framework adequate to usefully represent all goal-directed learning tasks? Can you think of any clear exceptions?</font>

<font color="green"><u><b>Answer</b></u></font>

Based on my current knowledge, I can come up with one use case. It's not really an exception but rather not that <font color="red">**optimization**</font> to use a **MDP**. One of that is **Trajectory planning**.

**Trajectory planning** is moving from point A to point B while avoiding collisions over time. This can be computed in both discrete and continuous methods. Trajectory planning is a major area in robotics as it gives way to autonomous vehicles.[1]

At first, it seems this scenario can be solved by using **MDP**. If it's a long one, I think it will be **Navigation** rather than **Trajectory**. 

One of a popular case would be **Trajectory for Robot Maniputator** such as industrail robot arms.

<image src="https://www.mathworks.com/responsive_image/165/120/0/0/0/cache/matlabcentral/mlc-downloads/downloads/0b300068-f139-417c-802c-5441b69b8c90/34c167e4-8005-4f71-9e8b-3693e5772d14/images/screenshot.png" />

Based on an above picture, using **MDP** is probably too overkilled. Based on this paper, "Calculation Methodology for Trajectory Planning
of a 6 axis manipulator arm [2]". I just skimmed through this paper and see that with the use of **Polynomial Method**, **Motion Kinematics Principle** and **Joint coordination** to establish the **Motion Equation** is suffix.

**MDP** would be too much for this scenario since the real world is under the known and controlled environment (in the cage or designate area inside a warehouse). There is not so much **undertainty** or any **complexity** in the real world that will effect the motion of the robot arms. 

We don't need to find an optimal path of the robot arm by finding the best path through the **value iteration policy** until it converge but instead using an equation to solve for that path in one go.

Based on this *StackExchange* [3], time complexity of the **value iteration policy** is O(|S×A|) for each update to a single V(s) estimate is $O(|S|^2|A|)$ while for the **Polynomial function** is $((a_{n}x+a{n-1})x+...)x+a_{0}$ using *Horner's Rule [4]*. 

By just looking the the time complexity of both cases from above, we can't say for sure which one is bigger. But, one thing we can say is that if the **state space $(|S|)$** is large, the time complexity of the **value iteration policy** will be fore sure much large than the **Polynomial function**.

[1] https://en.wikibooks.org/wiki/Robotics/Navigation/Trajectory_Planning#:~:text=Trajectory%20planning%20is%20moving%20from,gives%20way%20to%20autonomous%20vehicles.

[2] http://annals.fih.upt.ro/pdf-full/2018/ANNALS-2018-3-03.pdf

[3] https://ai.stackexchange.com/questions/9019/what-is-the-time-complexity-of-the-value-iteration-algorithm

[4] https://mathworld.wolfram.com/HornersRule.html

**(Exercise 3.7)** Imagine that you are designing a robot to run a maze. You decide to give it a reward of +1 for escaping from the maze and a reward of zero at all other times. The task seems to break down naturally into episodes—the successive runs through the maze—so you decide to treat it as an episodic task, where the goal is to maximize expected total reward (3.7). After running the learning agent for a while, you find that it is showing no improvement in escaping from the maze. What is going wrong? Have you effectively
communicated to the agent what you want it to achieve?

## Programming Exercises


**<font color="blue">(Exercise P1)** Adapt one of your solutions for assignment 5 (either policy iteration or value iteration, your choice) to another [toy text](https://gym.openai.com/envs/#toy_text) gym environment of your choice.</font>

<font color="green"><u><b>Answer</b></u></font>

Below code was adapted from assignment 5's solution but implement in numpy for the **Taxi-v3** toy text. The task is to Teach a Taxi to pick up and drop off passengers at the right locations with Reinforcement Learning by implementing a **Policy Iteration** to estimate $\pi_{*}$.

In [35]:
import gym
import numpy as np 
import torch

import warnings
warnings.filterwarnings('ignore')

# Set the environment
env = gym.make('Taxi-v3')   
env._max_episode_steps = 50
env.reset()

# Implement the policy evluation algorithm here given a policy and a complete model of the environment.
def policy_evaluation(policy, env, gamma=0.9, theta=1e-8):
    # Start with an all zero value function
    V = np.zeros(env.nS)
    while True:
        delta = 0
        for s in range(env.nS):
            v = 0
            for a in range(env.nA):
                for prob, nextState, reward, done in env.P[s][a]:
                    v+=policy[s][a] * prob * (reward + gamma*V[nextState])
            
            delta = max(delta, np.abs(v-V[s]))
            V[s] = v
                
        if delta < theta:
            break
    
    return np.array(V)

# Implement the Policy Improvement Algorithm here which iteratively evaluates and improves a policy until an optimal policy is found.
def policy_improvement(env, policy, policy_eval_fn=policy_evaluation, gamma=0.9):

    while True:  
        # Start with all zero action value  
        action_value = np.zeros([env.nS, env.nA])

        V = policy_eval_fn(policy, env, gamma)
        policy_stable = True
        
        for s in range(env.nS):
            old_action = np.argmax(policy[s])

            # Implement the function to calculate the value for all actions in a given state.
            for a in range(env.nA):
              for prob, nextState, reward, done in env.P[s][a]:
                action_value[s][a] += prob * (reward + gamma * V[nextState])

            new_action = np.argmax(action_value[s])

            if old_action != new_action:
                policy_stable = False
                        
            policy[s] = np.zeros([env.nA])
            policy[s][new_action] = 1

        if policy_stable:
            return policy, V
    
    return policy, np.zeros(env.env.nS)

In [36]:
# Initialize arbitrary: 25% each action
policy = np.ones([env.nS, env.nA]) / env.nA

policy_pi, value_pi = policy_improvement(env, policy, gamma=0.9)

In [34]:
import numpy as np
np.set_printoptions(threshold=np.inf)

# Show all value in numpy array of the optimal policy (policy pi)
print(policy_pi)

[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0.

**(Exercise P2)** The official PyTorch examples includes [an implementation of REINFORCE](https://github.com/pytorch/examples/blob/master/reinforcement_learning/reinforce.py), which represents the agent policy using a differentiable function (a neural network).  Adapt this implementation to the FrozenLake environment problem.



